name: allE2E

on:
  workflow_dispatch:
    inputs:
      in_dev:
        description: '是否是测试环境'
        default: 'false'
        
  # schedule:
  #   - cron: '5 */2 * * *'  # 每天自动进行E2E测试

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: 触发自动测试
        uses: actions/github-script@v7
        with:
          script: |
            const inDev = context.payload.inputs ? context.payload.inputs.in_dev : 'false';
            const taskList = inDev === "true" ? [
                {
                    workflow_id: "Windows10.yml",
                    client_payload: {
                        software_download_url: 'https://dev.thinkoncloud.cn/downloads/win10_app_zh/HuaYoungApp_Win10_dev_zh_setup.exe',
                        do_wdio: 'true',
                        in_dev: 'true',
                        do_ip_test: 'false',
                        debug: 'false'
                    }
                },
                {
                    workflow_id: "Windows7-docker.yml",
                    client_payload: {
                        software_download_url: 'https://dev.thinkoncloud.cn/downloads/win7_app_zh/HuaYoungApp_Win7_dev_zh_setup.exe',
                        in_dev: 'true',
                        tmate: 'false'
                    }
                },
                {
                    workflow_id: "macOS.yml",
                    client_payload: {
                        software_download_url: 'https://dev.thinkoncloud.cn/downloads/mac_arm64_app_zh/HuaYoungApp_Mac_arm64_dev_zh_setup.dmg',
                        in_dev: 'true',
                        runs_on: 'macos-latest'
                    }
                },
                {
                    workflow_id: "macOS.yml",
                    client_payload: {
                        software_download_url: 'https://dev.thinkoncloud.cn/downloads/mac_x64_app_zh/HuaYoungApp_Mac_x64_dev_zh_setup.dmg',
                        in_dev: 'true',
                        runs_on: 'macos-12'
                    }
                },
                {
                    workflow_id: "Linux.yml",
                    client_payload: {
                        software_download_url: 'https://dev.thinkoncloud.cn/downloads/ubuntu_app_zh/HuaYoungApp_Ubuntu_dev_zh_setup.deb',
                        in_dev: 'true'
                    }
                }
            ] : []

            for (let i = 0; i < taskList.length; i++) {
                let task = taskList[i];
                const response = await github.rest.actions.createWorkflowDispatch({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    ref: context.ref,
                    workflow_id: task.workflow_id,
                    inputs: task.inputs
                });
                console.log(response);
            }