name: 验证Win7能否启动

# https://github.com/actions/runner-images/issues/8730
# macos-12 20240105.3、20240119.1 才能正常跑
# macos-12 20240105.1   也启动不了win7
# https://github.com/actions/runner-images/releases/tag/macOS-12%2F20240105.3
# 更新进度: https://github.com/actions/runner-images

on:
  push:
    paths:
      - .github/workflows/ci-win7-verify.yml

  repository_dispatch:
    types: [retry-workflow-win7-verify]

jobs:
  vagrant-up:
    runs-on: macos-12

    steps:
      - name: Check Image Version
        run: |
          version=$(grep -oE 'Image Version: ([0-9]{8}\.[0-9])' ~/systeminfo.md | awk '{print $3}')
          required_version="20240119.1"

          if [[ $version == $required_version || $version > $required_version ]]; then
            echo "Image Version 大于等于 ${required_version}，可以正常工作"
          else
            echo "Image Version 小于 ${required_version}，退出工作流，发出retry-workflow事件重试。"
            exit 1
          fi

      - name: Rerun workflow
        if: failure()
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: ${{ github.repository }}
          event-type: retry-workflow-win7-verify
      
      # - name: Setup tmate session5
      #   uses: mxschmitt/action-tmate@v3

      - uses: actions/checkout@v4

      - name: Install Vagrant 2.3.6
        run: |
          brew uninstall vagrant
          wget https://releases.hashicorp.com/vagrant/2.3.6/vagrant_2.3.6_darwin_amd64.dmg
          hdiutil attach vagrant_2.3.6_darwin_amd64.dmg
          sudo installer -pkg /Volumes/Vagrant/vagrant.pkg -target /
          hdiutil detach /Volumes/Vagrant/
          vagrant --version

      - name: Show Vagrant version
        run: vagrant --version

      - name: 下载安装包
        run: |
          wget https://dev.thinkoncloud.cn/downloads/win7_app_zh/HuaYoungApp_Win7_dev_zh_setup.exe -O installer.exe

      - name: Copy files to Win7
        run: |
          find . -type f -not -path "*/\.*" -not -path "./win7/*" -exec cp {} ./win7/{} \;
          rm -rf win7/cmd.js
          cp win7/cmd_verify.js win7/cmd.js
          rm -rf win7/tests/*
          cp win7/min_verify.spec.js win7/tests

      - name: Run vagrant up
        run: vagrant up || true

      - name: 等待测试完成
        run: |
          while [ ! -f win7/done.log ]; do echo "等待文件 win7/done.log 出现..."; tail win7/start.log; sleep 5; done
          echo "文件 win7/done.log 已经出现"
          cat win7/done.log
          cat win7/start.log
          echo "测试结束"


      # - name: action-debug
      #   uses: fawazahmed0/action-debug@main

