name: CI

# https://github.com/actions/runner-images/issues/8730
# macos-12 20240105 才能正常跑
# https://github.com/actions/runner-images/releases/tag/macOS-12%2F20240105.3
# 更新进度: https://github.com/actions/runner-images

on:
  push:
    paths:
      - .github/workflows/ci-win7.yml
      - Vagrantfile


jobs:
  vagrant-up:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v2
      
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      
      # - name: Install Vagrant
      #   run: brew install vagrant --cask


      # - name: Cache Vagrant boxes
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/.vagrant.d/boxes
      #     key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
      #     restore-keys: |
      #       ${{ runner.os }}-vagrant-

      - name: Show Vagrant version
        run: vagrant --version

      - name: Run vagrant up
        run: vagrant up

      - name: ifconfig
        run: vagrant powershell -c ipconfig

      - name: 当前所在位置
        run: vagrant powershell -c "pwd"

      - name: 当前目录文件列表
        run: vagrant powershell -c "dir"

      - name: 上级目录文件列表
        run: vagrant powershell -c "dir ../"

      - name: ifconfig
        run: vagrant powershell -c '& ".\win7.bat"'
