name: CI

# https://github.com/actions/runner-images/issues/8730
# macos-12 20240105.3 才能正常跑
# https://github.com/actions/runner-images/releases/tag/macOS-12%2F20240105.3
# 更新进度: https://github.com/actions/runner-images

on:
  push:
    paths:
      - .github/workflows/ci-win7.yml
      - Vagrantfile
      - win7.bat

  repository_dispatch:
    types: [retry-workflow]

jobs:
  vagrant-up:
    runs-on: macos-12

    steps:
      - name: Check Image Version
        run: |
          grep "Image Version" ~/systeminfo.md
          if grep -q "20240105.3" ~/systeminfo.md; then
            echo "Image Version 正确"
          else
            echo "Image Version 不是20240105.3，退出工作流。"
            exit 1
          fi

      - name: Rerun workflow
        if: failure()
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.repository }}
          event-type: retry-workflow
      
      # - name: Setup tmate session5
      #   uses: mxschmitt/action-tmate@v3

      - uses: actions/checkout@v2
      
      - name: Install Vagrant 2.3.6
        run: |
          brew uninstall vagrant
          wget https://releases.hashicorp.com/vagrant/2.3.6/vagrant_2.3.6_darwin_amd64.dmg
          hdiutil attach vagrant_2.3.6_darwin_amd64.dmg
          sudo installer -pkg /Volumes/Vagrant/vagrant.pkg -target /
          hdiutil detach /Volumes/Vagrant/
          vagrant --version

      # - name: Cache Vagrant boxes
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/.vagrant.d/boxes
      #     key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
      #     restore-keys: |
      #       ${{ runner.os }}-vagrant-

      - name: Show Vagrant version
        run: vagrant --version

      - name: Run vagrant up
        run: vagrant up

      - name: ifconfig
        run: vagrant powershell -c ipconfig
      
      - name: Setup tmate session5
        uses: mxschmitt/action-tmate@v3

      - name: 当前所在位置
        run: vagrant powershell -c "pwd"

      - name: 当前目录文件列表
        run: vagrant powershell -c "dir"

      - name: 上级目录文件列表
        run: vagrant powershell -c "dir ../"

      - name: ifconfig
        run: vagrant powershell -c '& ".\win7.bat"'
