name: Win7-2

# https://github.com/actions/runner-images/issues/8730
# macos-12 20240105.3 才能正常跑
# macos-12 20240105.1   也启动不了win7
# https://github.com/actions/runner-images/releases/tag/macOS-12%2F20240105.3
# 更新进度: https://github.com/actions/runner-images

on:
  push:
    paths:
      - .github/workflows/ci-win7-2.yml
      - Vagrantfile2

  repository_dispatch:
    types: [retry-workflow-2]

jobs:
  vagrant-up:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v4

      - name: Install Vagrant 2.3.6
        run: |
          brew uninstall vagrant
          wget https://releases.hashicorp.com/vagrant/2.3.6/vagrant_2.3.6_darwin_amd64.dmg
          hdiutil attach vagrant_2.3.6_darwin_amd64.dmg
          sudo installer -pkg /Volumes/Vagrant/vagrant.pkg -target /
          hdiutil detach /Volumes/Vagrant/
          vagrant --version
          rm -rf Vagrantfile
          cp Vagrantfile2 Vagrantfile

      - name: Show Vagrant version@2
        run: vagrant --version

      - name: Run vagrant up
        run: |
          vagrant up || true
      
      - name: action-debug
        uses: fawazahmed0/action-debug@main

      - name: ifconfig
        run: vagrant powershell -c "node -v"
