name: 检查测试环境是否有新的安装包

on:
  schedule:
    - cron: '* * * * *'

jobs:
  check-file-modified:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: win10_last-modified
          path: downloaded_artifact

      - name: 对比Win10 last-modified
        id: win10-compare-modified
        run: |
          if [ -f downloaded_artifact/win10_last_modified.txt ]; then
            stored_date=$(cat downloaded_artifact/last_modified.txt)
            current_date=$(curl -sI https://dev.thinkoncloud.cn/downloads/win10_app_zh/HuaYoungApp_Win10_dev_zh_setup.exe | grep Last-Modified | awk -F': ' '{print $2}')
            
            if [ "$stored_date" != "$current_date" ]; then
              echo "::set-output name=modified::true"
              echo current_date > win10_last_modified.txt
            else
              echo "::set-output name=modified::false"
            fi
          fi

      - name: Save last-modified date to artifact
        if: steps.compare-modified-1.outputs.modified == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: win10_last-modified
          path: win10_last_modified.txt

      - name: Run task if modified
        if: steps.win10-compare-modified.outputs.modified == 'true' && needs.win10-task-execution.result != 'failure'
        id: win10-task-execution
        run: |
          # 执行您的任务
          echo "执行任务"