# Copyright: 2022 fpliu
# License: GPL-2.0-or-later

name: FreeBSD

on: [push]

jobs:
  test:
    runs-on: macos-12

    strategy:
      fail-fast: false
      matrix:
        version: [13]

    steps:
      - uses: leleliu008/github-actions-vagrant@main
        with:
          mem: 2048
          box: generic/freebsd${{ matrix.version }}
          log: debug
          run: |
            run id
            run pwd
            run export -p
            run pkg install -y git
            touch aaa

      - run: printf '%s\n' "$VAGRANT_CWD"
      - run: scp -i $VAGRANT_CWD/.vagrant/machines/default/virtualbox/private_key -o StrictHostKeyChecking=no -r -P 2222 vagrant@127.0.0.1:/home/vagrant/leleliu008/github-actions-vagrant/aaa .
