name: Mac-latest_VNC
on: 
  workflow_dispatch:
jobs:
  build:
    name: Mac-latest_VNC
    runs-on: macos-latest
    
    steps:     
    
    - uses: actions/checkout@v4 

    - name: Enabling Remote Access
      run: |
          chmod +x ./macOS_VNC/start.sh
          sudo ./macOS_VNC/start.sh
          
    - name: Log In Details To VNC Server
      run: |
         chmod +x ./macOS_VNC/login.sh
         sudo ./macOS_VNC/login.sh
          
    - name: Enable screen recording
      run: |
        sudo chmod +x ./macOS_VNC/modify_screensharing-14.sh
        sudo ./macOS_VNC/modify_screensharing-14.sh
        sudo ./macOS_VNC/enable_vnc.sh

    - name: 启动frpc
      run: |
        sed -i "" "s/user = .*/user = ${{ secrets.FRPC_USER }}/g" macOS_VNC/frpc_15897721.ini
        sed -i "" "s/remote_port = .*/remote_port = ${{ secrets.FRPC_MAC_REMOTE_PORT }}/g" macOS_VNC/frpc_15897721.ini
        sed -i "" "s/local_port = .*/local_port = 5900/g" macOS_VNC/frpc_15897721.ini
        curl -Lo frpc https://nya.globalslb.net/natfrp/client/frpc/0.51.0-sakura-9.3/frpc_darwin_arm64
        chmod +x frpc
        ./frpc -c ./macOS_VNC/frpc_15897721.ini > /tmp/frpc.log 2>&1 &

    - name: MacOS System running...
      uses: mxschmitt/action-tmate@v2