name: macOS

on:
  repository_dispatch:
    types: [macOS-start]
    
  workflow_dispatch:
    inputs:
      software_download_url:
        description: 'Download url'
        required: true
        default: 'https://dl.szdamai.com/downloads/mac_arm64_app_zh/HuaYoungApp_Mac_arm64_10.0.559_zh_setup.dmg'
      in_dev:
        description: '是否是测试环境'
        default: 'false'
      runs_on:
        # https://docs.github.com/zh/actions/reference/runners/github-hosted-runners#standard-github-hosted-runners-for-public-repositories
        description: 'macos-14(arm64)、macos-15(arm64)还是macos-15-intel(x64)'
        default: 'macos-latest'

jobs:

  macOS:
    runs-on: ${{ github.event.inputs.runs_on }}

    steps:

      # - name: Intentionally Fail
      #   run: exit 1  # 此处退出状态为1，表示故意失败

      - name: Check if running on M1 chip # github Action的macOS机器似乎都是M1芯片
        run: |
          if [[ "$(sysctl -n machdep.cpu.brand_string)" == *"Apple"* ]]; then
            echo "Running on an Apple Silicon (M1) chip"
          else
            echo "Running on an Intel chip"
          fi

      - uses: actions/checkout@v4
      
      - name: 下载并安装客户端
        run: |
          if [ -z "${{ inputs.software_download_url }}" ]; then
            download_url="https://dl.szdamai.com/downloads/mac_arm64_app_zh/HuaYoungApp_Mac_arm64_10.0.559_zh_setup.dmg"
          else
            download_url="${{ inputs.software_download_url }}"
          fi
          curl -o /tmp/HuaYoungApp_Mac_setup.dmg $download_url

          # 挂载dmg
          hdiutil attach /tmp/HuaYoungApp_Mac_setup.dmg

          # 查找第一个以“花漾客户端”开头的目录
          appDir=$(find /Volumes -maxdepth 1 -type d -name "花漾客户端*" | head -n 1)
          echo "appDir: $appDir"

          sudo cp -R "${appDir}/花漾客户端.app" /Applications/
          hdiutil detach "${appDir}"
          if [ -f "/Applications/花漾客户端.app/Contents/Resources/app.asar" ]; then
            sudo chmod -f a+w /Applications/花漾客户端.app/Contents/Resources/app.asar
          fi

      # - name: Start software
      #   run: |
      #     open /Applications/花漾客户端.app

      - name: 准备chromedriver
        run: |
          if [[ "$(sysctl -n machdep.cpu.brand_string)" == *"Apple"* ]]; then
            echo "M1芯片下chromedirver路径是：/tmp/chromedriver/mac_arm-108/chromedriver-mac-arm64/chromedriver"
            mkdir -p /tmp/chromedriver/mac_arm-108/chromedriver-mac-arm64/
            cp tools/chromedriver/108.0.5359.71/mac-arm64/chromedriver /tmp/chromedriver/mac_arm-108/chromedriver-mac-arm64/
            chmod +x /tmp/chromedriver/mac_arm-108/chromedriver-mac-arm64/chromedriver
            echo "E2E_PLATFORM=macOS-arm64" >> $GITHUB_ENV
          else
            echo "Intel芯片下chromedirver路径是：/tmp/chromedriver/mac-108/chromedriver-mac-x64/chromedriver"
            mkdir -p /tmp/chromedriver/mac-108/chromedriver-mac-x64/
            cp tools/chromedriver/108.0.5359.71/mac-x64/chromedriver /tmp/chromedriver/mac-108/chromedriver-mac-x64/
            chmod +x /tmp/chromedriver/mac-108/chromedriver-mac-x64/chromedriver
            echo "E2E_PLATFORM=macOS-x64" >> $GITHUB_ENV
          fi

      - name: Use Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'yarn'
          
      - name: Install dependencies 👨🏻‍💻
        run: yarn

      - name: 自动创建工作目录
        run: |
          mkdir -p ~/Library/Application\ Support/HuaYoung

      - name: E2E Test for Electron 🧪
        env:
          DEV_WDIO_PASSWORD: ${{ secrets.DEV_WDIO_PASSWORD }}
          PRODUCT_WDIO_PASSWORD: ${{ secrets.PRODUCT_WDIO_PASSWORD }}
          DOWNLOAD_URL: ${{ github.event.inputs.software_download_url }}
          IN_DEV: ${{ github.event.inputs.in_dev }}
          FEISHU_TOKEN: ${{ secrets.FEISHU_TOKEN }}
          FEISHU_ME: ${{ secrets.FEISHU_ME }}
          LOGGER_SERVER: ${{ secrets.LOGGER_SERVER }}
          TRANSITER_SH_SERVER: ${{ secrets.TRANSITER_SH_SERVER }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          CLOUDINARY_URL: ${{ secrets.CLOUDINARY_URL }}
          CLOUDINARY_MASK: ${{ secrets.CLOUDINARY_MASK }}
        run: sudo node modifyMain.js && node tests/start.js e2e

      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3