name: Notify on Failure

on:
  workflow_run:
    workflows: [Windows10, Windows7-docker, macOS, Ubuntu]
    types:
      - completed

jobs:
  notify:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest

    steps:
      # - name: Print GitHub Event
      #   env:
      #     GITHUB_EVENT: ${{ toJson(github.event) }}  # 将事件信息转换为 JSON 字符串
      #   run: |
      #     echo "GitHub Event:"
      #     echo "${GITHUB_EVENT}"  # 打印 GitHub 事件的详细信息

      - name: Send notification to Feishu
        env:
          FEISHU_TOKEN: ${{ secrets.FEISHU_TOKEN }}
          FEISHU_ME: ${{ secrets.FEISHU_ME }}
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"content":{"text": "【花漾】Workflow failed: ${{ github.event.workflow.name }}\n<at user_id=\"'"${FEISHU_ME}"'\">me</at>(github actions request)"},"msg_type":"text"}' https://open.feishu.cn/open-apis/bot/v2/hook/$FEISHU_TOKEN
