name: Check File for String

on:
  push:
    paths:
      - .github/workflows/repository-dispatch-test.yml

jobs:
  check-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check file for string
        run: |
          echo "wi2n10" > a.txt
          if grep -q "win10" a.txt; then
            echo "File contains 'win10'. Dispatching event..."
            echo "WIN10_MODIFIED=true" >> $GITHUB_ENV
          else
            echo "File does not contain 'win10'."
            echo "WIN10_MODIFIED=false" >> $GITHUB_ENV
          fi
          
      - name: Dispatch event
        if: env.WIN10_MODIFIED == 'true'
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: windows10-dispatch
