name: Vagrant Up

on:
  push:
    paths:
      - .github/workflows/vagrant-verify.yml

permissions:
  contents: read

jobs:
  vagrant-up:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v4
      - run: brew install virtualbox vagrant
      - run: cp Vagrantfile-verify Vagrantfile
      # Installing this is skipped in CI as using it was causing some corruption in
      # attempting to mount the shared folder. The guest and host guest additions
      # versions are close enough that we are fine without it.
      # - run: vagrant plugin install vagrant-vbguest
      - run: NO_SUBMISSIONS=1 vagrant up