name: Windows7-docker

on:
  workflow_dispatch:

jobs:
  Windows7:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        
      - name: 启动docker
        run: |
          cd win7
          docker-compose up -d

      - name: 启动frpc
        run: |
          curl -Lo frpc https://nya.globalslb.net/natfrp/client/frpc/0.51.0-sakura-5.1/frpc_linux_amd64
          chmod +x frpc
          ./frpc -c ./win7/frpc_16020852.ini &

      - name: Setup tmate session5
        if: ${{ !contains(inputs.tmate, 'false') }}
        uses: mxschmitt/action-tmate@v3
        continue-on-error: true

      - name: 等待测试完成
        run: |
          while ! inotifywait -e create win7/done.log; do echo "等待文件 win7/done.log 出现..."; done; echo "文件 win7/done.log 已经出现"
          cat win7/done.log
          cat win7/start.log
          echo "测试结束"

      # - name: action-debug
      #   uses: fawazahmed0/action-debug@main

