name: Windows7-docker

on:
  workflow_dispatch:
    inputs:
      software_download_url:
        description: 'Download url'
        required: true
        default: 'https://dl.szdamai.com/downloads/win7_app_zh/HuaYoungApp_Win7_10.2.563_zh_setup.exe'
      in_dev:
        description: '是否是测试环境'
        default: 'false'

jobs:
  Windows7:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        
      - name: 启动docker
        run: |
          cd win7
          docker-compose up -d

      - name: 下载补丁和nodejs
        run: |
          wget https://download.microsoft.com/download/4/E/8/4E864B31-7756-4639-8716-0379F6435016/Windows6.1-KB3080149-x64.msu
          wget https://nodejs.org/dist/v18.20.3/node-v18.20.3-win-x64.zip
          wget https://chromedriver.storage.googleapis.com/108.0.5359.71/chromedriver_win32.zip
          unzip node-v18.20.3-win-x64.zip
          unzip chromedriver_win32.zip

      - name: 保存密码
        env:
          DEV_WDIO_PASSWORD: ${{ secrets.DEV_WDIO_PASSWORD }}
          PRODUCT_WDIO_PASSWORD: ${{ secrets.PRODUCT_WDIO_PASSWORD }}
          IN_DEV: ${{ github.event.inputs.in_dev }}
          FEISHU_TOKEN: ${{ secrets.FEISHU_TOKEN }}
        run: |
          echo '{
            "DEV_WDIO_PASSWORD": "'"${DEV_WDIO_PASSWORD}"'",
            "PRODUCT_WDIO_PASSWORD": "'"${PRODUCT_WDIO_PASSWORD}"'",
            "IN_DEV": "'"${IN_DEV}"'",
            "FEISHU_TOKEN": "'"${FEISHU_TOKEN}"'"
          }' > passwd.json
      
      - name: 下载客户端
        run: |
          if [ -z "${{ inputs.software_download_url }}" ]; then
            download_url="https://dl.szdamai.com/downloads/win7_app_zh/HuaYoungApp_Win7_10.2.563_zh_setup.exe"
          else
            download_url="${{ inputs.software_download_url }}"
          fi
          curl -o installer.exe $download_url

      - name: Copy files to Win7
        run: |
          find . -type f -not -path "*/\.*" -not -path "./win7/*" -exec rsync --relative {} ./win7/shared/work \;
        
      - name: 复制相关文件到虚拟机共享目录
        run: |
          cd win7
          cp ../Windows6.1-KB3080149-x64.msu ./shared
          cp ../installer.exe ./shared/work
          cp ../chromedriver.exe ./shared/work
          cp ../passwd.json ./shared/work
          cp -r ../node-v18.20.3-win-x64 ./shared/node

      - name: 启动frpc
        run: |
          curl -Lo frpc https://nya.globalslb.net/natfrp/client/frpc/0.51.0-sakura-5.1/frpc_linux_amd64
          chmod +x frpc
          ./frpc -c ./win7/frpc_16020852.ini &

      - name: Setup tmate session5
        if: ${{ !contains(inputs.tmate, 'false') }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 25
        continue-on-error: true

      - name: 等待测试完成
        run: |
          while [ ! -f "/var/win7/share/done.log" ]; do
              sleep 10
          done
          echo "File /var/win7/share/done.log found!"
          cat win7/share/start.log
          cat win7/share/done.log
          echo "测试结束"

      # - name: action-debug
      #   uses: fawazahmed0/action-debug@main

      - name: Save Logs on Error
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: win7/share/start.log

