name: Windows10

on:
  repository_dispatch:
    types: [win10-start]
    
  workflow_dispatch:
    inputs:
      software_download_url:
        description: 'Download url'
      do_wdio:
        description: '是否执行 WDIO 测试'
        default: ''
      in_dev:
        description: '是否是测试环境'
        default: 'false'
      do_ip_test:
        description: '是否执行 IP 测试'
        default: 'true'
      debug:
        description: '是否开启调试'
        default: 'false'
        
  schedule:
    - cron: '5 */3 * * *'  # 每隔两个小时自动进行IP测试

jobs:

  Windows10:
    runs-on: windows-latest
    
    steps:
      - name: 显示输入参数
        if: ${{ inputs.do_ip_test != '' }}
        run: |
          Write-Output ${{ inputs.do_ip_test }} 
    
      - uses: actions/checkout@v4

      - name: Use Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'yarn'
          
      - name: Install dependencies 👨🏻‍💻
        run: yarn

      - name: 安装客户端
        run: |
          $ErrorActionPreference = "Stop"

          try {
            # 检查是否提供了下载 URL
            if ( -not "${{ github.event.inputs.software_download_url }}" ) {
              # 没有提供 URL，从 JSON 中获取版本号
              try {
                $url = "https://www.szdamai.com/static.config.json"
                $response = Invoke-RestMethod -Uri $url
                $appVersion = $response.windows10AppVersion

                # 根据版本号构建下载 URL
                $downloadUrl = "https://dl.szdamai.com/downloads/win10_app_zh/HuaYoungApp_Win10_${appVersion}_zh_setup.exe"
                Write-Host "Generated download URL: $downloadUrl"
              } catch {
                Write-Error "获取版本信息失败: $_"
                exit 1
              }
            } else {
              # 使用提供的下载 URL
              $downloadUrl = "${{ github.event.inputs.software_download_url }}"
              Write-Host "Using provided download URL: $downloadUrl"
            }

            # 下载客户端安装包
            try {
              Invoke-WebRequest -Uri $downloadUrl -OutFile "$env:TEMP\your_software_installer.exe"
              Write-Host "下载成功: $downloadUrl"
            } catch {
              Write-Error "下载安装包失败: $_"
              exit 1
            }

            # 安装客户端
            try {
              Start-Process -FilePath "$env:TEMP\your_software_installer.exe" -ArgumentList "/S" -Wait -Verb RunAs
              Write-Host "安装完成"
            } catch {
              Write-Error "安装客户端失败: $_"
              exit 1
            }

            $filePath = "C:\Program Files\HuaYoung\花漾客户端.exe"
            $timeoutMinutes = 5  # 最大等待时间（分钟）
            $checkIntervalSeconds = 10  # 检查间隔（秒）
            $endTime = (Get-Date).AddMinutes($timeoutMinutes)

            Write-Host "等待文件出现: $filePath"
            Write-Host "最大等待时间: $timeoutMinutes 分钟"

            while ((Get-Date) -lt $endTime) {
                if (Test-Path -Path $filePath -PathType Leaf) {
                    Write-Host "文件已找到: $filePath"

                    # 启动软件
                    # Start-Process -FilePath "$env:LOCALAPPDATA\Programs\HuaYoung\花漾客户端.exe"
                    # exe的路径已经变了
                    try {
                      Start-Process -FilePath "$filePath"
                      Write-Host "软件启动成功"
                      exit 0
                    } catch {
                      Write-Error "启动软件失败: $_"
                      exit 1
                    }
                }

                $remainingTime = $endTime - (Get-Date)
                $remainingMinutes = [math]::Round($remainingTime.TotalMinutes, 1)
                Write-Host "文件未找到，剩余等待时间: $remainingMinutes 分钟，将在 $checkIntervalSeconds 秒后再次检查..."
                Start-Sleep -Seconds $checkIntervalSeconds
            }

            Write-Error "超时错误: 在 $timeoutMinutes 分钟内未找到文件 $filePath"
            exit 1

          } catch {
            Write-Error "安装过程发生未预期的错误: $_"
            exit 1
          }


      - name: 检查安装目录是否存在
        run: |
          Test-Path "$env:LOCALAPPDATA\Programs\HuaYoung\花漾客户端.exe"
          
      - name: 复制Chrome Driver到指定临时目录
        run: |
          # 目标目录路径
          $destinationPath = "$env:TEMP\chromedriver\win64-108\chromedriver-win64"
          $destinationFile = "$destinationPath\chromedriver.exe"

          # 确保目标目录存在
          if (-not (Test-Path -Path $destinationPath)) {
              New-Item -Path $destinationPath -ItemType Directory -Force
          }

          # 执行文件复制
          Copy-Item -Path "./tools/chromedriver/108.0.5359.71/win32/chromedriver.exe" -Destination $destinationFile -Force

      - name: 检查Chrome Driver
        run: |
          Get-ChildItem -Path "$env:TEMP\chromedriver\win64-108"

      - name: 花漾运行目录不存在时创建
        run: |
          if not exist "C:\Users\%USERNAME%\AppData\Roaming\HuaYoung" (
            mkdir "C:\Users\%USERNAME%\AppData\Roaming\HuaYoung"
          )
        shell: cmd

      - name: Enable TS
        if: ${{ contains(inputs.debug, 'true') }}
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
          Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

      - name: 修改分辨率为1920*1080
        run: |
          Set-DisplayResolution -Width 1920 -Height 1080 -Force

      # - name: 下载以前的执行结果
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: e2e-result

      - name: 启动frpc
        if: ${{ contains(inputs.debug, 'true') }}
        run: |
          (Get-Content macOS_VNC/frpc_15897721.ini) -replace "user = .*", "user = $env:FRPC_USER" | Set-Content macOS_VNC/frpc_15897721.ini
          (Get-Content macOS_VNC/frpc_15897721.ini) -replace "remote_port = .*", "remote_port = $env:FRPC_MAC_REMOTE_PORT" | Set-Content macOS_VNC/frpc_15897721.ini
          (Get-Content macOS_VNC/frpc_15897721.ini) -replace "local_port = .*", "local_port = 3389" | Set-Content macOS_VNC/frpc_15897721.ini
          Invoke-WebRequest -Uri "https://nya.globalslb.net/natfrp/client/frpc/0.51.0-sakura-12.3/frpc_windows_amd64.exe" -OutFile "frpc.exe"
          ./frpc.exe -c macOS_VNC/frpc_15897721.ini
        env:
          FRPC_USER: ${{ secrets.FRPC_USER }}
          FRPC_MAC_REMOTE_PORT: ${{ secrets.FRPC_MAC_REMOTE_PORT }}

      - name: E2E Test for Electron 🧪
        if: ${{ contains(inputs.do_wdio, 'true') }}
        env:
          E2E_PLATFORM: "Windows 10"
          DEV_WDIO_PASSWORD: ${{ secrets.DEV_WDIO_PASSWORD }}
          PRODUCT_WDIO_PASSWORD: ${{ secrets.PRODUCT_WDIO_PASSWORD }}
          DOWNLOAD_URL: ${{ github.event.inputs.software_download_url }}
          IN_DEV: ${{ github.event.inputs.in_dev }}
          FEISHU_TOKEN: ${{ secrets.FEISHU_TOKEN }}
          FEISHU_ME: ${{ secrets.FEISHU_ME }}
          LOGGER_SERVER: ${{ secrets.LOGGER_SERVER }}
          TRANSITER_SH_SERVER: ${{ secrets.TRANSITER_SH_SERVER }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          CLOUDINARY_URL: ${{ secrets.CLOUDINARY_URL }}
          CLOUDINARY_MASK: ${{ secrets.CLOUDINARY_MASK }}
        run: node modifyMain.js && node tests\start.js e2e

      - name: IP测试
        if: ${{ !contains(inputs.do_ip_test, 'false') }}
        env:
          PRODUCT_IP_TEST_PASSWORD: ${{ secrets.PRODUCT_IP_TEST_PASSWORD }}
          FEISHU_TOKEN: ${{ secrets.FEISHU_TOKEN }}
          FEISHU_ME: ${{ secrets.FEISHU_ME }}
          LOGGER_SERVER: ${{ secrets.LOGGER_SERVER }}
          TRANSITER_SH_SERVER: ${{ secrets.TRANSITER_SH_SERVER }}
          CLOUDINARY_URL: ${{ secrets.CLOUDINARY_URL }}
          CLOUDINARY_MASK: ${{ secrets.CLOUDINARY_MASK }}
        run: node tests\start.js ipTest