name: Windows7

on:
  repository_dispatch:
    types: [win7-start, retry-win7-start]
    
  workflow_dispatch:
    inputs:
      tmate:
        description: "开启ssh调试"
        default: "false"

jobs:
  Windows7:
    runs-on: ubuntu-latest
    timeout-minutes: 600

    steps:
      - uses: actions/checkout@v4
      
      - name: Install Vagrant
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg |  sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo  "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $( lsb_release -cs ) main"  |  sudo  tee /etc/apt/sources.list.d/hashicorp.list
          sudo  apt update &&  sudo  apt  install vagrant

      # - name: Cache Vagrant boxes
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/.vagrant.d/boxes
      #     key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
      #     restore-keys: |
      #       ${{ runner.os }}-vagrant-

      - name: Show Vagrant version
        run: vagrant --version

      - name: 下载安装包
        run: |
          wget https://dev.thinkoncloud.cn/downloads/win7_app_zh/HuaYoungApp_Win7_dev_zh_setup.exe -O installer.exe

      - name: Copy files to Win7
        run: |
          find . -type f -not -path "*/\.*" -not -path "./win7/*" -exec rsync --relative {} ./win7/ \;

      - name: Run vagrant up
        run: vagrant up || true

      - name: Setup tmate session5
        if: ${{ !contains(inputs.tmate, 'false') }}
        uses: mxschmitt/action-tmate@v3
        continue-on-error: true
        timeout-minutes: 30  # 设置超时时间为30分钟

      - name: 等待测试完成
        run: |
          while ! inotifywait -e create win7/done.log; do echo "等待文件 win7/done.log 出现..."; done; echo "文件 win7/done.log 已经出现"
          cat win7/done.log
          cat win7/start.log
          echo "测试结束"

      # - name: action-debug
      #   uses: fawazahmed0/action-debug@main

