name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Enable TS
        run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
      - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
      - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
      - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
      - name: 启动frpc
        run: |
          sed -i "s/user = .*/user = ${{ secrets.FRPC_USER }}/g" macOS_VNC/frpc_15897721.ini
          sed -i "s/remote_port = .*/remote_port = ${{ secrets.FRPC_MAC_REMOTE_PORT }}/g" macOS_VNC/frpc_15897721.ini
          sed -i "s/local_port = .*/local_port = 3389/g" macOS_VNC/frpc_15897721.ini
          curl -Lo frpc https://nya.globalslb.net/natfrp/client/frpc/0.51.0-sakura-5.1/frpc_darwin_arm64
          chmod +x frpc
          ./frpc -c ./macOS_VNC/frpc_15897721.ini > /tmp/frpc.log 2>&1 &